services:

  postgres:
    image: postgres:16
    container_name: zap-mesa_postgres
    restart: always
    environment:
      POSTGRES_USER: zapmesa
      POSTGRES_PASSWORD: zapmesa123
      POSTGRES_DB: zapmesa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: zap-mesa-backend
    restart: always
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: zap-mesa-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: