FROM node:22 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate --schema src/prisma/schema.prisma
RUN npm run build

FROM node:22 AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=build /app/dist ./dist
COPY --from=build /app/src/prisma ./src/prisma
COPY --from=build /app/prisma.config.ts ./prisma.config.ts

RUN npx prisma generate --schema src/prisma/schema.prisma

EXPOSE 3333

CMD ["node", "dist/server.js"]
